### ISSUE TITLE
IMSProg collaboration

### ISSUE THREAD

**Issue by AndreiCherniaev** [AndersBNielsen/Relatively-Universal-ROM-Programmer#1]
Hello. There is [IMSProg](https://github.com/bigbigmdm/IMSProg) software for modern programmer device. I suggest you to check is it good idea to adopt this software for your Relatively Universal-ROM-Programmer.

**Comment by AndersBNielsen** [comment]
As far as I can tell that's only for serial EEPROM CH341 based programmers. Quite a different beast. I don't see any similarity or anything that would be able to handle parallel programming - except for a bit of GUI, it's basically everything from scratch. 
For now I plan to get programming via serial port working with a python script on the host side and enough "on device" code to handle all features via serial. Certainly wouldn't mind some help wrapping it in a nice GUI eventually - I'm not convinced IMSProg is a good fit.

**Comment by AndreiCherniaev** [comment]
Thank you for response!

**Comment by AndersBNielsen** [comment]
Yeah, this isn't going to happen. Closing.
