### ISSUE TITLE
Change github About

### ISSUE THREAD

**Issue by AndreiCherniaev** [AndersBNielsen/Relatively-Universal-ROM-Programmer#2]
I suggest to add About text (right top corner of github)
_Hardware to program W27C512 EEPROM or any 24/28/32 pin ROM requiring from 5V to 27V programming voltage._

I also suggest you to add tags:
**chip-programmer
prom-writer**

**Comment by AndersBNielsen** [comment]
@AndreiCherniaev Thank you! Implemented :)
