### ISSUE TITLE
Please please please replace the Micro-USB connector with a USB-C connector 🙏🏾

### ISSUE THREAD

**Issue by volkertb** [AndersBNielsen/Relatively-Universal-ROM-Programmer#3]
Hi Anders,

I just watched your announcement on YouTube, and first of all: a big THANK YOU for releasing this project with the world! :hugs:

I remember a few years ago having to find a good USB ROM programmer on-line that would come with open source Linux drivers. Although I eventually found one, it was not easy. Nor was it cheap, even for a used one.

So having a programmer that has both an open source hardware design and open source software support is really the best of both worlds. And for such a low price too! Your contribution will indeed help a lot of hobbyists, tinkerers and perhaps even some professional electronics engineers worldwide!

But I have to admit that while watching your video, there was one thing that broke my heart. And no, it wasn't the red LEDs.

The Micro-USB connector. :scream: Is there any deliberate reason why you picked it over USB-C?

There appears to be enough space in the corner to accommodate a USB-C connector instead. And it might increase the total costs of the design by a little, but I cannot imagine that it would be that much more expensive.

I don't think I have to rattle off all the advantages that USB-C has over the abomination that is Micro-USB. I think that's all pretty obvious.

Say what you will about those expensive commercial ROM programmers, but those old-school USB Type B connectors sure were durable and sturdy. I know that a Type B connector on your programmer design would probably be overkill, but please consider using USB-C in your design instead.

If there is any reason why this wouldn't be feasible, maybe you can explain in this thread?

Thanks again! Looking forward to seeing this project improve and thrive. :heart:

**Comment by bleroy** [comment]
Maybe I'm missing something, but I'm pretty sure the USB connector is on whatever Arduino clone you choose to use with the board, not on the programmer board itself. Soooo.... pick a board with USB-C?

**Comment by volkertb** [comment]
Ah, you're right. It goes on top of another board as a HAT. I should have realized that. 🤦🏽‍♂️

Sorry for the misunderstanding, then. In case you hadn't noticed, I hate the Micro-USB connector like the plague and got immediately triggered when I saw it as part of a new project. :sweat_smile:

Thanks for clarifying!
