### ISSUE TITLE
can't read a rom of size 0x8000 bytes or greater

### ISSUE THREAD

**Issue by BizarroBull** [AndersBNielsen/Relatively-Universal-ROM-Programmer#4]
I'm trying to read 32768 bytes. I'm using a block size of 32 and a stop page of 0x80.
When calculating the ROM size by bit shifting 0x80, romsize becomes 0xFFFF8000.
You need to cast the int result of Serial.read() to a uint32_t.

I made the following change on my fork to get it working:

	romsize = (static_cast<uint32_t>(Serial.read()) << 8); //Reads stoppage a.k.a. the high byte of ROM size

**Comment by AndersBNielsen** [comment]
Merged :)
